export const CRYPTO_LIST_REQUEST = 'CRYPTO_LIST_REQUEST';
export const CRYPTO_LIST_SUCCESS = 'CRYPTO_LIST_SUCCESS';
export const CRYPTO_LIST_FAIL = 'CRYPTO_LIST_FAIL';
export const CRYPTO_LIST_RESET = 'CRYPTO_LIST_RESET';

export const CRYPTO_DETAILS_REQUEST = 'CRYPTO_DETAILS_REQUEST';
export const CRYPTO_DETAILS_SUCCESS = 'CRYPTO_DETAILS_SUCCESS';
export const CRYPTO_DETAILS_FAIL = 'CRYPTO_DETAILS_FAIL';
export const CRYPTO_DETAILS_RESET = 'CRYPTO_DETAILS_RESET';

export const CHART_REQUEST = 'CHART_REQUEST';
export const CHART_FAIL = 'CHART_FAIL';
export const CHART_RESET = 'CHART_RESET';

export const MONTH_CHART_SUCCESS = 'MONTH_CHART_SUCCESS';
export const WEEK_CHART_SUCCESS = 'WEEK_CHART_SUCCESS';
export const DAY_CHART_SUCCESS = 'DAY_CHART_SUCCESS';

export const ADD_COIN_PORTFOLIO_REQUEST = 'ADD_COIN_PORTFOLIO_REQUEST';
export const ADD_COIN_PORTFOLIO_SUCCESS = 'ADD_COIN_PORTFOLIO_SUCCESS';
export const ADD_COIN_PORTFOLIO_FAIL = 'ADD_COIN_PORTFOLIO_FAIL';
export const ADD_COIN_PORTFOLIO_RESET = 'ADD_COIN_PORTFOLIO_RESET';

export const COIN_LIST_MY_REQUEST = 'COIN_LIST_MY_REQUEST';
export const COIN_LIST_MY_SUCCESS = 'COIN_LIST_MY_SUCCESS';
export const COIN_LIST_MY_FAIL = 'COIN_LIST_MY_FAIL';
export const COIN_LIST_MY_RESET = 'COIN_LIST_MY_RESET';
