export const CRYPTO_LIST_REQUEST = 'CRYPTO_LIST_REQUEST';
export const CRYPTO_LIST_SUCCESS = 'CRYPTO_LIST_SUCCESS';
export const CRYPTO_LIST_FAIL = 'CRYPTO_LIST_FAIL';
export const CRYPTO_LIST_RESET = 'CRYPTO_LIST_RESET';

export const CRYPTO_DETAILS_REQUEST = 'CRYPTO_DETAILS_REQUEST';
export const CRYPTO_DETAILS_SUCCESS = 'CRYPTO_DETAILS_SUCCESS';
export const CRYPTO_DETAILS_FAIL = 'CRYPTO_DETAILS_FAIL';
export const CRYPTO_DETAILS_RESET = 'CRYPTO_DETAILS_RESET';

export const CHART_REQUEST = 'CHART_REQUEST';
export const CHART_FAIL = 'CHART_FAIL';
export const CHART_RESET = 'CHART_RESET';

export const MONTH_CHART_SUCCESS = 'MONTH_CHART_SUCCESS';
export const WEEK_CHART_SUCCESS = 'WEEK_CHART_SUCCESS';
export const DAY_CHART_SUCCESS = 'DAY_CHART_SUCCESS';
