export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';

export const SEARCH_NEWS_REQUEST = 'SEARCH_NEWS_REQUEST';
export const SEARCH_NEWS_SUCCESS = 'SEARCH_NEWS_SUCCESS';
export const SEARCH_NEWS_FAIL = 'SEARCH_NEWS_FAIL';
