export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';
export const MOVIE_LIST_RESET = 'MOVIE_LIST_RESET';

export const MOVIE_SHOW = 'MOVIE_SHOW';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';
export const MOVIE_DETAILS_RESET = 'MOVIE_DETAILS_RESET';

export const MOVIE_ORDER_CREATE_REQUEST = 'MOVIE_ORDER_CREATE_REQUEST';
export const MOVIE_ORDER_CREATE_SUCCESS = 'MOVIE_ORDER_CREATE_SUCCESS';
export const MOVIE_ORDER_CREATE_FAIL = 'MOVIE_ORDER_CREATE_FAIL';
export const MOVIE_ORDER_CREATE_RESET = 'MOVIE_ORDER_CREATE_RESET';

export const MOVIE_CREDITS = 'MOVIE_CREDITS';
export const BUY_MOVIE_CREDITS_SUCCESS = 'BUY_MOVIE_CREDITS_SUCCESS';
export const BUY_MOVIE_CREDITS_FAIL = 'BUY_MOVIE_CREDITS_FAIL';

export const MOVIE_LIST_MY_REQUEST = 'MOVIE_LIST_MY_REQUEST';
export const MOVIE_LIST_MY_SUCCESS = 'MOVIE_LIST_MY_SUCCESS';
export const MOVIE_LIST_MY_FAIL = 'MOVIE_LIST_MY_FAIL';
export const MOVIE_LIST_MY_RESET = 'MOVIE_LIST_MY_RESET';

export const MOVIE_RETURN_REQUEST = 'MOVIE_RETURN_REQUEST';
export const MOVIE_RETURN_SUCCESS = 'MOVIE_RETURN_SUCCESS';
export const MOVIE_RETURN_FAIL = 'MOVIE_RETURN_FAIL';
